In [1]:
#! nvidia-smi

In [2]:
#conda install pytorch torchvision -c pytorch

In [3]:
import os
def EXIT_NOTEBOOK(): os._exit(00)
#os.environ['CUDA_VISIBLE_DEVICES'] = '3'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
import random
import torch 
from torch import nn
import torch.nn.functional as func
import seaborn as sns
import matplotlib.ticker

# # ps
# import pysindy as ps

# sns.set_theme()
# torch.set_default_dtype(torch.float32)
plt.rcParams['text.usetex'] = True

In [5]:
dim = 6
torch.set_default_dtype(torch.float64)

# Dataset for X

In [6]:
from BeadModel import Simulate
from SimulationParameters import *

X = Simulation(*Simulate(numSims)).positions[:,:,:,0].reshape(-1,11).T
# Z = X.view

print(X.shape)
print(X)

(11, 6)
[[ 0.00181041 -0.00368259  0.0132552  -0.00035438 -0.00631434  0.03265687]
 [-0.01004892  0.01748322  0.03745173 -0.03301874 -0.01342641  0.02331496]
 [-0.00939654  0.01554023  0.04545922 -0.0300129  -0.02676867  0.00163342]
 [ 0.01056262  0.01302863 -0.00110986 -0.01965036 -0.05146543  0.02239085]
 [ 0.0219014  -0.00981768  0.01192202 -0.01483939 -0.04021126  0.00640442]
 [ 0.02757576 -0.05462983  0.02740565 -0.02563909 -0.03631639 -0.0168472 ]
 [ 0.04279456 -0.07608843  0.025036   -0.02655259 -0.02304651 -0.01648925]
 [ 0.04673986 -0.06923174  0.03891451 -0.00474065 -0.0366756  -0.00304013]
 [ 0.05801875 -0.0759003   0.03121408  0.01319496 -0.02757106  0.02100878]
 [ 0.04967904 -0.06564827  0.03206785  0.00911454 -0.00639907  0.01831608]
 [ 0.04967904 -0.06564827  0.03206785  0.00911454 -0.00639907  0.01831608]]


# Set the NN model and Solver with training process

In [7]:
def relu2(X): return func.relu(X)**2
def tanh(X): return func.tanh(X)
class FCNN(nn.Module):
    def __init__(self,input_dim=6,output_dim=6,num_hidden=2,hidden_dim=10,act=func.tanh,transform=None):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.layers  = nn.ModuleList([nn.Linear(input_dim,hidden_dim)])
        for _ in range(num_hidden-1): self.layers.append(nn.Linear(hidden_dim,hidden_dim))
        self.act     = act
        self.out     = nn.Linear(hidden_dim,output_dim)
        self.transform = transform
    def forward(self,X):
        if self.transform is not None: X = self.transform(X)
        for layer in self.layers: X = self.act(layer(X))
        Y = self.out(X)
        return Y
class Model(nn.Module):
    def __init__(self,dim,model_U,unit_len=int(5e3)):
        super().__init__()
        self.dim      = dim
        self.model_U  = model_U
        self.unit_len = unit_len
        self.mu       = nn.Parameter(torch.tensor([0.]*dim),requires_grad=False) 
        self.sigma    = nn.Parameter(torch.tensor([1.]*dim),requires_grad=False)
        #above two lines should work, but if something doesn't work, check here! Does current self.mu and self.sigma code work if dim>1. Should return a vector since what we're trying to do is calculate mu
        #and sigma separately for each imnputted feature. mu is parameter[0] for each row.
        self.coef_U   = nn.Parameter(torch.tensor([1.]*dim),requires_grad=False)
        #self.mu       = nn.Parameter(torch.tensor([0.]*dim).cuda(),requires_grad=False)
        #self.sigma    = nn.Parameter(torch.tensor([1.]*dim).cuda(),requires_grad=False)
        #self.coef_U   = nn.Parameter(torch.tensor(1.).cuda(),requires_grad=False)
    def get_U_harmonic(self,X): return torch.sum(X**2,axis=-1)
        
    # def get_U_dU(self, X):
    #     U_list = []
    #     dU_list = []
    #     for t in range(X.shape[-1]):
    #         X_t = X[..., t]
    #         X_t_ = torch.tensor(X_t, dtype=torch.float32, requires_grad=True)
    #         # X_t_ = (X_t - self.mu) / self.sigma #normalization necessary, column wise is standard
    #         # U_t = torch.sum(self.coef_U * (self.model_U(X_t_) + self.get_U_harmonic(X_t_))) #*certify validity
    #         print()
    #         print(self.coef_U)
    #         print()
    #         print(self.model_U(X_t_))
    #         print()
    #         print(self.get_U_harmonic(X_t_))
    #         print()
    #         U_t = self.coef_U[t] * (self.model_U(X_t_)) #Perhaps this is just supposed to be integrated the dU at each time step.
    #         U_list.append(U_t)
    #         dU_t = torch.autograd.grad(
    #             outputs=U_t,
    #             inputs=X_t,
    #             grad_outputs=torch.ones_like(U_t),
    #             create_graph=True
    #         )[0]
    #         dU_list.append(dU_t)
    #     U = torch.stack(U_list, dim=0)
    #     dU = torch.stack(dU_list, dim=-1)
    #     return U, dU
    
    def get_U_dU(self,X):
        # normalize and ensure x is a tensor
        if not torch.is_tensor(X): X = torch.tensor(X, requires_grad=True)
        U = self.model_U(X).view(-1)
        dU = torch.autograd.grad(U, X, torch.ones_like(U), create_graph=True)[0]
        dU = dU.view(-1)
        return U,dU

    
    def get_U_np(self,X): 
        U,_ = self.get_U_dU(X);
        return U.cpu().data.numpy()
    
class Solver():
    def __init__(self,model):
        self.model=model
    def train_model(self,data_train,data_test,get_loss,optimizer,
                    n_steps,batch_size,scheduler=None,n_show_loss=100,error_model=None,use_tqdm=True):
        if use_tqdm: step_range = tqdm(range(n_steps))
        else: step_range = range(n_steps)
        loss_step = []
        for i_step in step_range:
            if i_step%n_show_loss==0:
                loss_train,loss_test = get_loss(self.model,data_train)[:-1],\
                                       get_loss(self.model,data_test)[:-1]
                
                def show_num(x): 
                    if abs(x)<100 and abs(x)>.01: return '%0.5f'%x
                    else: return '%0.2e'%x
                item1 = '%2dk'%np.int_(i_step/1000)
                item2 = 'Loss: '+' '.join([show_num(k) for k in loss_train])
                item3 = ' '.join([show_num(k) for k in loss_test])
                item4 = ''
                if error_model is not None: item4 = 'E(QP): %0.4f' % (error_model(self.model))
                print(', '.join([item1,item2,item3,item4]))
                loss_step = loss_step + [i_step] + [k.cpu().data.numpy() for k in loss_train]\
                                                 + [k.cpu().data.numpy() for k in loss_train]
            data_batch = data_train[random.sample(range(len(data_train)),
                                                  min(batch_size,len(data_train)))]
#             print(i_step,data_batch.shape)
            loss = get_loss(self.model,data_batch)[-1]
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            if scheduler is not None: scheduler.step()
        if error_model is not None: 
            print("Error: %0.5f" % (error_model(self.model)))
        return loss_step

In [8]:
model_U = FCNN(input_dim=dim,output_dim=1,num_hidden=3,hidden_dim=10,act=tanh)#.cuda()
model   = Model(dim,model_U=model_U)#.cuda();
SOL     = Solver(model)

In [9]:
# model.get_U_dU(X[:3])

In [10]:
# print(model.mu.shape)
# print(model.mu)

# Set the loss function and Train the model for differen a_k(x)

In [11]:
from Loss import getResidue

# def plot_model(model,cmap='terrain',max_V = 10):
    
#     xx     = np.linspace(0,2,1000).reshape(-1,1)
#     U_NN   = model.get_U_np(xx)
#     U_NN_min = U_NN.min()
#     U_NN  = U_NN-U_NN_min

#     fig, ax    = plt.subplots(1,1,figsize=(5,3),dpi=200,constrained_layout=True)
#     c      = ax.plot(xx[:,0],U_NN,'-',lw=1.5,)

#     ax.tick_params(axis="both", labelsize=10)
#     plt.show()
#def get_a(X,k=choose_id):
#    if choose_id==1: return 2*torch.exp(-3*X**2)
#    if choose_id==2: return 2/(1+torch.exp(20*(torch.abs(X)-0.75)))
#    if choose_id==3: return 4/(1+torch.exp(20*(torch.abs(X)-0.75)))
def get_loss(model,data):
    X = data
    X = torch.tensor(X).clone().detach().requires_grad_(True)
    _,dU = model.get_U_dU(X)
    loss = getResidue(X, dU)
    return loss#,loss



# plot_model(model)
get_loss(model,X[0,:])

torch.Size([6])
tensor([ 0.0018, -0.0037,  0.0133, -0.0004, -0.0063,  0.0327],
       requires_grad=True)

torch.Size([3, 2])
tensor([[ 0.0018, -0.0037],
        [ 0.0133, -0.0004],
        [-0.0063,  0.0327]], grad_fn=<ViewBackward0>)


RuntimeError: The size of tensor a (2) must match the size of tensor b (6) at non-singleton dimension 1

In [57]:
print(X[:3])
print()
print(X)

[[-0.00243799  0.01924196  0.00951585  0.01997272  0.02274476  0.02197342
   0.02988516  0.03016298  0.03775648  0.0325914   0.0325914 ]
 [ 0.00038227 -0.01836769 -0.02576915 -0.03428247 -0.00521031 -0.01486312
  -0.0088077  -0.01159346 -0.01876385 -0.03125893 -0.03125893]
 [-0.00081651 -0.00429388 -0.03085536 -0.0340672  -0.0294273  -0.0043999
   0.00132315  0.02195165  0.01560272 -0.00895788 -0.00895788]]

[[-0.00243799  0.01924196  0.00951585  0.01997272  0.02274476  0.02197342
   0.02988516  0.03016298  0.03775648  0.0325914   0.0325914 ]
 [ 0.00038227 -0.01836769 -0.02576915 -0.03428247 -0.00521031 -0.01486312
  -0.0088077  -0.01159346 -0.01876385 -0.03125893 -0.03125893]
 [-0.00081651 -0.00429388 -0.03085536 -0.0340672  -0.0294273  -0.0043999
   0.00132315  0.02195165  0.01560272 -0.00895788 -0.00895788]
 [-0.02518475 -0.02601089 -0.02921433 -0.05514915 -0.06113394 -0.05267548
  -0.05440637 -0.04828464 -0.05494695 -0.08005298 -0.08005298]
 [-0.0184581  -0.01354045 -0.02817425 -0.

In [84]:
#for choose_id in [1,2,3]:
model_U = FCNN(input_dim=dim,output_dim=1,num_hidden=3,hidden_dim=10,act=tanh)#.cuda()
model   = Model(dim,model_U=model_U)#.cuda();
SOL     = Solver(model)

print(model.mu,model.sigma,model.coef_U)
    #optimizer = torch.optim.Adam(model.parameters(), lr=torch.tensor(0.001).cuda())
optimizer = torch.optim.Adam(model.parameters(), lr=torch.tensor(0.001))
scheduler = None
_loss_step = SOL.train_model(data_train=X,data_test=X,
                             get_loss=get_loss,optimizer=optimizer,scheduler=scheduler,
                             n_steps=int(5e4+1),batch_size=500,n_show_loss=1000,use_tqdm=True)
torch.cuda.empty_cache()
plot_model(model)
   # torch.save(model.state_dict(), "savee/model_"+str(choose_id))
#torch.save(model.state_dict(),"savee/model_anaconda3")

<bound method Module.type of FCNN(
  (layers): ModuleList(
    (0): Linear(in_features=6, out_features=10, bias=True)
    (1-2): 2 x Linear(in_features=10, out_features=10, bias=True)
  )
  (out): Linear(in_features=10, out_features=1, bias=True)
)>
Parameter containing:
tensor([0., 0., 0., 0., 0., 0.]) Parameter containing:
tensor([1., 1., 1., 1., 1., 1.]) Parameter containing:
tensor(1.)


  0%|          | 0/50001 [00:00<?, ?it/s]

/var/folders/jf/w5m4c3sj361fdh8b5wz1cy1m0000gn/T/ipykernel_89714/972852114.py:41: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_t_ = torch.tensor(X_t, dtype=torch.float32, requires_grad=True)


RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Double

In [108]:
#torch.save(model.state_dict(), "savee/model_99")
#model.state_dict()

In [ ]:
fig, ax  = plt.subplots(1,1,figsize=(4,3),dpi=200,constrained_layout=True)
xx       = np.linspace(0,2,1000).reshape(-1,1)
U_NN     = model.get_U_np(xx)
U_NN_min = U_NN.min()
U_NN     = U_NN-U_NN_min
c        = ax.plot(xx[:,0],U_NN,'-',lw=1.5)
ax.legend(fontsize=10)
ax.set_xlabel('$x$',fontsize=10)
ax.set_ylabel('$U(x)$',fontsize=10)
ax.set_xlim([0,2])
ax.set_yticks([0,0.2,0.4,0.6,0.8,1,1.2])
ax.set_xticks([0,.5,1.,1.5,2])
ax.yaxis.grid(linestyle='--')
ax.tick_params(axis="both", labelsize=10)
plt.show()

In [ ]:
U_NN

In [30]:
import scipy.io as scio
from scipy.io import savemat


# Visualizing the results for different a_k(x)

In [ ]:
def plot_models(models):
    
    xx       = np.linspace(0,2,1000).reshape(-1,1)
    fig, ax  = plt.subplots(1,1,figsize=(4,3),dpi=200,constrained_layout=True)
    
    for k,model_name in enumerate(models):
        model.load_state_dict(torch.load(model_name))
        U_NN     = model.get_U_np(xx)
        U_NN_min = U_NN.min()
        U_NN     = U_NN-U_NN_min
        c        = ax.plot(xx[:,0],U_NN,'-',lw=1.5,label="$a_{%d}(x)$"%(k+1))
    ax.legend(fontsize=10)
    ax.set_xlabel('$x$',fontsize=10)
    ax.set_ylabel('$U(x)$',fontsize=10)
    ax.set_xlim([0,2])
    ax.set_yticks([0,0.2,0.4,0.6,0.8,1,1.2])
    ax.set_xticks([0,.5,1.,1.5,2])
    ax.yaxis.grid(linestyle='--')
    ax.tick_params(axis="both", labelsize=10)
    plt.show()
    
plot_models(["savee/model_anaconda3"])
#plot_models(["savee/model_a1_update", "savee/model_a2_update", "savee/model_a3_update", "savee/model_a4", "savee/model_a5_update"])

In [ ]:
model

In [ ]:
torch.load("/Users/annacoletti/Desktop/savee/model_a3_update.mat")