In [29]:
import torch
import pandas as pd
from GetLoss import getResidue

paths = torch.tensor(pd.read_csv('alpha1_path.txt', header = None).values)
gradients = torch.tensor(pd.read_csv('alpha1_dW.txt', header = None).values)

paths = paths.T.reshape(-1,3,2)
gradients = gradients.T.reshape(-1,3,2)


In [30]:
results = []
for i in range(10):
    results.append(getResidue(paths[i,:,:], gradients[i,:,:]).item())
print(results)

tensor([[-1.5000e+00,  5.0000e-01,  5.0000e-01,  5.0000e-01],
        [ 2.0000e+00, -5.0000e-01,  0.0000e+00,  0.0000e+00],
        [ 3.4853e-04,  0.0000e+00, -5.0000e-01,  0.0000e+00],
        [ 3.4853e-04,  0.0000e+00,  0.0000e+00, -5.0000e-01]])
tensor([[-1.5001e+00,  5.0000e-01,  5.0000e-01,  5.0000e-01],
        [ 2.0000e+00, -4.9645e-01,  0.0000e+00,  0.0000e+00],
        [ 8.5087e-04,  0.0000e+00, -8.8522e-01,  0.0000e+00],
        [ 5.5935e-04,  0.0000e+00,  0.0000e+00, -6.8988e-01]])
tensor([[-1.5026e+00,  5.0000e-01,  5.0000e-01,  5.0000e-01],
        [ 2.0000e+00, -4.9487e-01,  0.0000e+00,  0.0000e+00],
        [ 2.0769e-03,  0.0000e+00, -8.9124e-01,  0.0000e+00],
        [ 8.6152e-04,  0.0000e+00,  0.0000e+00, -7.0765e-01]])
tensor([[-1.5048e+00,  5.0000e-01,  5.0000e-01,  5.0000e-01],
        [ 2.0000e+00, -4.9191e-01,  0.0000e+00,  0.0000e+00],
        [ 5.0662e-03,  0.0000e+00, -8.8938e-01,  0.0000e+00],
        [ 1.3549e-03,  0.0000e+00,  0.0000e+00, -6.9605e-01]])
tens

In [31]:
# print(paths.shape)
# print(paths)

In [32]:
# print(gradients.shape)
# print(gradients)